# -*- coding: utf-8 -*-
"""intern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MutwcHWXzHCnENzj-UA5tNlcg_E9dxq7
"""

# Core libraries
!pip install ultralytics streamlit joblib pyngrok opencv-python-headless -q

# Segmentation libraries
!pip install segmentation-models-pytorch albumentations -q

from google.colab import drive
drive.mount('/content/drive')

import torch
import segmentation_models_pytorch as smp

# Create U-Net model
unet_model = smp.Unet(
    encoder_name="resnet34",
    encoder_weights="imagenet",
    in_channels=3,
    classes=1
)

print("U-Net model created for vegetation/ruin segmentation")

def iou_score(pred, target):
    intersection = (pred & target).float().sum()
    union = (pred | target).float().sum()
    return intersection / (union + 1e-6)

def dice_score(pred, target):
    intersection = (pred * target).sum()
    return (2 * intersection) / (pred.sum() + target.sum() + 1e-6)

print("IoU and Dice Score functions ready")

loss_fn = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(unet_model.parameters(), lr=0.0001)

print("Segmentation training setup ready")

from ultralytics import YOLO
from google.colab import drive

drive.mount('/content/drive')

# Load trained model
yolo_model = YOLO("/content/drive/MyDrive/archaeology_best.pt")

print("Artifact detection model ready")

# Example metrics from training
metrics = {
    "mAP": 0.78,
    "precision": 0.82,
    "recall": 0.75
}

print("Detection Evaluation Metrics:")
print(metrics)

import numpy as np
import joblib
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

np.random.seed(42)
n_samples = 500

slope = np.random.uniform(0,50,n_samples)
vegetation = np.random.uniform(0,1,n_samples)
elevation = np.random.uniform(0,2000,n_samples)

erosion_risk = (
    0.5*(slope/50) +
    0.35*(1-vegetation) +
    0.15*(elevation/2000)
)

erosion_risk += np.random.normal(0,0.03,n_samples)
erosion_risk = np.clip(erosion_risk,0,1)

X = np.column_stack([slope,vegetation,elevation])
y = erosion_risk

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

model = RandomForestRegressor(
    n_estimators=200,
    max_depth=10
)

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

print("MSE:",mean_squared_error(y_test,y_pred))
print("R2:",r2_score(y_test,y_pred))

joblib.dump(model,"/content/drive/MyDrive/erosion_model.pkl")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/app.py
# 
# import streamlit as st
# import cv2
# import numpy as np
# from ultralytics import YOLO
# import joblib
# import zipfile
# import io
# 
# st.set_page_config(page_title="AI Archaeological Mapping", layout="wide")
# 
# st.title("AI Archaeological Site Mapping Platform")
# 
# # -------------------------------
# # Load Models
# # -------------------------------
# @st.cache_resource
# def load_models():
#     yolo = YOLO("/content/drive/MyDrive/archaeology_best.pt")
#     erosion = joblib.load("/content/drive/MyDrive/erosion_model.pkl")
#     return yolo, erosion
# 
# model, erosion_model = load_models()
# 
# 
# # -------------------------------
# # Vegetation Index (VARI)
# # -------------------------------
# def calculate_vari(image):
# 
#     img = image.astype(float)
# 
#     red = img[:,:,2]
#     green = img[:,:,1]
#     blue = img[:,:,0]
# 
#     vari = (green-red)/(green+red-blue+0.0001)
# 
#     vari = np.clip(vari,-1,1)
#     vari = (vari+1)/2
# 
#     return vari
# 
# 
# # -------------------------------
# # Vegetation Segmentation
# # -------------------------------
# def vegetation_segmentation(image,vari):
# 
#     seg = np.zeros_like(image)
# 
#     very_dense = vari > 0.7
#     dense = (vari > 0.5) & (vari <= 0.7)
#     medium = (vari > 0.35) & (vari <= 0.5)
#     sparse = (vari > 0.2) & (vari <= 0.35)
#     bare = vari <= 0.2
# 
#     seg[very_dense] = [255,0,0]
#     seg[dense] = [0,255,0]
#     seg[medium] = [0,0,255]
#     seg[sparse] = [200,200,200]
#     seg[bare] = [255,255,255]
# 
#     return seg
# 
# 
# # -------------------------------
# # Build KML
# # -------------------------------
# def build_kml(latitude,longitude,artifact_points):
# 
#     artifacts=""
# 
#     for i,_ in enumerate(artifact_points):
# 
#         artifacts+=f"""
#         <Placemark>
#         <name>Artifact {i+1}</name>
#         <Point>
#         <coordinates>{longitude+i*0.0001},{latitude+i*0.0001},0</coordinates>
#         </Point>
#         </Placemark>
#         """
# 
#     return f"""
# <?xml version="1.0" encoding="UTF-8"?>
# <kml xmlns="http://www.opengis.net/kml/2.2">
# 
# <Document>
# 
# <Placemark>
# <name>Site</name>
# <Point>
# <coordinates>{longitude},{latitude},0</coordinates>
# </Point>
# </Placemark>
# 
# {artifacts}
# 
# </Document>
# 
# </kml>
# """
# 
# 
# # -------------------------------
# # Build KMZ
# # -------------------------------
# def build_kmz(kml):
# 
#     buffer=io.BytesIO()
# 
#     with zipfile.ZipFile(buffer,"w",zipfile.ZIP_DEFLATED) as kmz:
#         kmz.writestr("doc.kml",kml)
# 
#     buffer.seek(0)
# 
#     return buffer.getvalue()
# 
# 
# if "artifact_points" not in st.session_state:
#     st.session_state.artifact_points=[]
# 
# if "veg_index" not in st.session_state:
#     st.session_state.veg_index=0.0
# 
# 
# col1,col2=st.columns([1,1])
# 
# 
# # -------------------------------
# # LEFT PANEL
# # -------------------------------
# with col1:
# 
#     st.subheader("Upload Satellite Image")
# 
#     uploaded=st.file_uploader(
#         "Upload image",
#         type=["jpg","jpeg","png","tif"]
#     )
# 
#     if uploaded:
# 
#         file_bytes=np.asarray(bytearray(uploaded.read()),dtype=np.uint8)
# 
#         image=cv2.imdecode(file_bytes,cv2.IMREAD_COLOR)
# 
#         # Resize large images for faster processing
#         h,w=image.shape[:2]
#         if w>1280:
#             scale=1280/w
#             image=cv2.resize(image,(int(w*scale),int(h*scale)))
# 
#         st.image(
#             cv2.cvtColor(image,cv2.COLOR_BGR2RGB),
#             caption="Uploaded Image",
#             use_container_width=True
#         )
# 
# 
#         # -------------------------------
#         # Artifact Detection
#         # -------------------------------
#         with st.spinner("Detecting artifacts..."):
#             results=model(image)
# 
#         detected_img=image.copy()
# 
#         artifact_points=[]
# 
#         for r in results:
# 
#             detected_img=r.plot()
# 
#             boxes=r.boxes.xyxy.cpu().numpy()
# 
#             for box in boxes:
# 
#                 x1,y1,x2,y2=box
# 
#                 artifact_points.append(
#                     (int((x1+x2)/2),int((y1+y2)/2))
#                 )
# 
#         st.session_state.artifact_points=artifact_points
# 
# 
#         st.subheader(f"Detected Artifacts: {len(artifact_points)}")
# 
#         st.image(
#             cv2.cvtColor(detected_img,cv2.COLOR_BGR2RGB),
#             use_container_width=True
#         )
# 
# 
#         # -------------------------------
#         # Vegetation Index
#         # -------------------------------
#         vari=calculate_vari(image)
# 
#         st.session_state.veg_index=float(vari.mean())
# 
#         st.subheader("Vegetation Index")
# 
#         st.image(
#             vari,
#             clamp=True,
#             use_container_width=True
#         )
# 
#         st.metric(
#             "Mean Vegetation Index",
#             round(st.session_state.veg_index,3)
#         )
# 
# 
#         # -------------------------------
#         # Vegetation Segmentation
#         # -------------------------------
#         st.subheader("Vegetation Segmentation Map")
# 
#         seg=vegetation_segmentation(image,vari)
# 
#         st.image(
#             cv2.cvtColor(seg,cv2.COLOR_BGR2RGB),
#             use_container_width=True
#         )
# 
# 
#         st.markdown("""
# 
# ### Vegetation Color Legend
# 
# 🔵 Blue — Very Dense Vegetation
# 🟢 Green — Dense Vegetation
# 🔴 Red — Moderate Vegetation
# ⬜ White — Bare Soil
# ⬛ Gray — Sparse Vegetation
# 
# """)
# 
# 
# # -------------------------------
# # RIGHT PANEL
# # -------------------------------
# with col2:
# 
#     st.subheader("Terrain Analysis")
# 
#     slope=st.slider("Slope (degrees)",0,50,10)
# 
#     elev=st.slider("Elevation (meters)",0,2000,300)
# 
#     if st.button("Predict Erosion Risk"):
# 
#         pred=erosion_model.predict(
#             [[slope,st.session_state.veg_index,elev]]
#         )
# 
#         score=float(pred[0])
# 
#         if score<0.33:
# 
#             st.success(f"Erosion Risk: {round(score,3)} — Low")
# 
#         elif score<0.66:
# 
#             st.warning(f"Erosion Risk: {round(score,3)} — Moderate")
# 
#         else:
# 
#             st.error(f"Erosion Risk: {round(score,3)} — High")
# 
# 
#     st.divider()
# 
#     st.subheader("Coordinates")
# 
#     latitude=st.number_input("Latitude",value=20.5937)
# 
#     longitude=st.number_input("Longitude",value=78.9629)
# 
#     st.divider()
# 
# 
#     earth_url=f"https://earth.google.com/web/@{latitude},{longitude},500a"
# 
#     st.markdown(f"[Open in Google Earth]({earth_url})")
# 
#     maps_url=f"https://www.google.com/maps/@{latitude},{longitude},15z"
# 
#     st.markdown(f"[Open in Google Maps]({maps_url})")
# 
# 
#     kml=build_kml(latitude,longitude,st.session_state.artifact_points)
# 
#     kmz=build_kmz(kml)
# 
#     st.download_button(
#         "Download KMZ",
#         data=kmz,
#         file_name="site.kmz",
#         mime="application/vnd.google-earth.kmz"
#     )

!pip install pyngrok -q
from pyngrok import ngrok, conf
import subprocess, threading, time

conf.get_default().auth_token="3AtWgN2zfyrD3GFojOArACPzuD0_5UgVZSUt3TmqAhG4KhXUG"

def run():
    subprocess.run(["streamlit","run","/content/app.py","--server.port","8501"])

threading.Thread(target=run).start()
time.sleep(10)

url = ngrok.connect(8501)
print("APP LIVE AT:",url)

