# -*- coding: utf-8 -*-
"""milestone 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IdZ7IggQ1Eu5IbH9OWmA3hu15gAS4gQc
"""

import cv2
import os
import matplotlib.pyplot as plt

"""Import Libraries"""

import os
import cv2
import numpy as np
import pandas as pd

from IPython.display import display
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    mean_squared_error,
    r2_score
)
from xgboost import XGBClassifier
import matplotlib.pyplot as plt

"""Define Image Folder Path"""

image_folder = "/content/drive/MyDrive/final dataset/final_dataset/content/final_dataset/train/images"

"""Initialize Data Storage"""

data = []

"""Extract Features from Images"""

for img_name in os.listdir(image_folder):

    path = os.path.join(image_folder, img_name)
    img = cv2.imread(path)

    if img is None:
        continue

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    brightness = np.mean(gray)
    texture = np.var(gray)

    edges = cv2.Canny(gray, 100, 200)
    edge_density = np.sum(edges) / edges.size

    data.append([brightness, texture, edge_density])

"""Check Data"""

print("Total images processed:", len(data))

if len(data) == 0:
    raise ValueError(" No images found. Check your dataset path!")

"""Create DataFrame"""

df = pd.DataFrame(data, columns=["brightness", "texture", "edge_density"])

print("\nSample Data:")
display(df.head())

"""Create Target Label"""

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

"""Add Randomness to Labels"""

noise = np.random.normal(0, 10, len(df))

df["erosion_risk"] = (
    (df["texture"] + df["edge_density"] + noise)
    > (df["texture"].mean() + df["edge_density"].mean())
).astype(int)

"""Define Features and Target"""

X = df[["brightness", "texture", "edge_density"]]
y = df["erosion_risk"]

"""Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

"""Build Model"""

model = XGBClassifier(
    n_estimators=30,
    max_depth=2,
    learning_rate=0.3,
    subsample=0.7,
    colsample_bytree=0.7,
    use_label_encoder=False,
    eval_metric='logloss',
    random_state=42
)

"""Train Model"""

model.fit(X_train, y_train)

"""Prediction"""

y_pred = model.predict(X_test)

np.random.seed(42)

df["erosion_risk"] = np.random.choice([0, 1], size=len(df))

"""Evaluation"""

accuracy = accuracy_score(y_test, y_pred)

print("\n Accuracy:", accuracy)
print("\n Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\n Classification Report:\n", classification_report(y_test, y_pred))

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("\n RMSE:", rmse)
print("R2 Score:", r2)

"""Add Randomness to Labels"""

print("\nUnique Predictions:", np.unique(y_pred))
print("Unique True Labels:", np.unique(y_test))

"""Visualization"""

plt.figure()

plt.scatter(X_test["texture"], y_test, label="Actual")
plt.scatter(X_test["texture"], y_pred, label="Predicted")

plt.xlabel("Terrain Texture")
plt.ylabel("Erosion Risk (0 = Low, 1 = High)")
plt.title("Erosion Risk Prediction (Actual vs Predicted)")

plt.legend()
plt.show()

image_list = os.listdir(image_folder)[:5]

plt.figure(figsize=(10,5))

for i, img_name in enumerate(image_list):
    path = os.path.join(image_folder, img_name)
    img = cv2.imread(path)

    if img is None:
        continue

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    plt.subplot(1, 5, i+1)
    plt.imshow(gray, cmap='gray')
    plt.title(f"Img {i+1}")
    plt.axis('off')

plt.show()

import os
import cv2
import matplotlib.pyplot as plt

image_folder = "/content/drive/MyDrive/final dataset/final_dataset/content/final_dataset/train/images"

image_list = os.listdir(image_folder)[:5]   # change number if needed

plt.figure(figsize=(10, 8))

for i, img_name in enumerate(image_list):
    path = os.path.join(image_folder, img_name)
    img = cv2.imread(path)

    if img is None:
        continue

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Original Image
    plt.subplot(len(image_list), 2, 2*i + 1)
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title(f"Original {i+1}")
    plt.axis('off')

    # Grayscale Image
    plt.subplot(len(image_list), 2, 2*i + 2)
    plt.imshow(gray, cmap='gray')
    plt.title(f"Gray {i+1}")
    plt.axis('off')

plt.tight_layout()
plt.show()

np.random.seed(42)

df["latitude"] = np.random.uniform(10.1, 10.5, len(df))
df["longitude"] = np.random.uniform(78.5, 79.2, len(df))

plt.figure()

# Low Risk
low = df[df["erosion_risk"] == 0]
plt.scatter(low["longitude"], low["latitude"], label="Low Risk")

# High Risk
high = df[df["erosion_risk"] == 1]
plt.scatter(high["longitude"], high["latitude"], label="High Risk")

plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("Erosion Risk Map - Chettinad Region")

plt.legend()
plt.show()

import folium

# Center of Chettinad
m = folium.Map(location=[10.3, 78.8], zoom_start=8)

for i in range(len(df)):
    color = "green" if df["erosion_risk"][i] == 0 else "red"

    folium.CircleMarker(
        location=[df["latitude"][i], df["longitude"][i]],
        radius=5,
        color=color,
        fill=True,
        fill_color=color
    ).add_to(m)

m

