# -*- coding: utf-8 -*-
"""milestone 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQNgfwqc2XBkBr2Ab98tb0UUcU0fvNjS
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile

zip_path = "/content/drive/MyDrive/chettinad.v1i.yolov8.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/dataset")

print("Dataset extracted successfully")

import os

print(len(os.listdir("/content/dataset/train/images")))
print(len(os.listdir("/content/dataset/train/labels")))

import os
print(os.listdir("/content/dataset/train"))

import os
import cv2
import numpy as np

input_folder = "/content/dataset/train/images"
output_folder = "/content/processed_dataset/images"

os.makedirs(output_folder, exist_ok=True)

img_size = (224,224)

for img in os.listdir(input_folder):

    img_path = os.path.join(input_folder,img)

    image = cv2.imread(img_path)

    if image is None:
        continue

    resized = cv2.resize(image,img_size)

    normalized = resized/255.0

    normalized_img = (normalized*255).astype(np.uint8)

    cv2.imwrite(os.path.join(output_folder,img),normalized_img)

print("Resizing and normalization completed")

import shutil

shutil.copytree("/content/dataset/train/labels",
                "/content/processed_dataset/labels",
                dirs_exist_ok=True)

import os
import shutil

# Step 1: Create base folders
base_path = "/content/processed_dataset"

folders = [
    "images/train",
    "images/val",
    "labels/train",
    "labels/val"
]

for folder in folders:
    os.makedirs(os.path.join(base_path, folder), exist_ok=True)

print("Folders created successfully ✅")

!pip install scikit-learn

import os
import shutil
from sklearn.model_selection import train_test_split

image_path="/content/processed_dataset/images"
label_path="/content/processed_dataset/labels"

# Filter to get only files, not directories, from the processed_dataset/images folder
all_entries = os.listdir(image_path)
images = [f for f in all_entries if os.path.isfile(os.path.join(image_path, f))]

train_imgs,temp_imgs=train_test_split(images,test_size=0.3,random_state=42)

val_imgs,test_imgs=train_test_split(temp_imgs,test_size=0.5,random_state=42)

import os
import shutil
from sklearn.model_selection import train_test_split

def move_files(files, img_dest, lbl_dest):
    # Ensure destination directories exist
    os.makedirs(img_dest, exist_ok=True)
    os.makedirs(lbl_dest, exist_ok=True)

    for img in files:
        label = img.replace(".jpg", ".txt")

        shutil.copy(os.path.join(image_path, img),
                    os.path.join(img_dest, img))

        shutil.copy(os.path.join(label_path, label),
                    os.path.join(lbl_dest, label))


# Define base path for final dataset
final_base_path = "/content/final_dataset"

# Create subdirectories for the final dataset
os.makedirs(os.path.join(final_base_path, "train", "images"), exist_ok=True)
os.makedirs(os.path.join(final_base_path, "train", "labels"), exist_ok=True)
os.makedirs(os.path.join(final_base_path, "val", "images"), exist_ok=True)
os.makedirs(os.path.join(final_base_path, "val", "labels"), exist_ok=True)
os.makedirs(os.path.join(final_base_path, "test", "images"), exist_ok=True)
os.makedirs(os.path.join(final_base_path, "test", "labels"), exist_ok=True)


move_files(train_imgs,
           os.path.join(final_base_path, "train", "images"),
           os.path.join(final_base_path, "train", "labels"))

move_files(val_imgs,
           os.path.join(final_base_path, "val", "images"),
           os.path.join(final_base_path, "val", "labels"))

move_files(test_imgs,
           os.path.join(final_base_path, "test", "images"),
           os.path.join(final_base_path, "test", "labels"))

print("Dataset split completed")

os.listdir("/content/final_dataset")

import shutil

shutil.make_archive("processed_dataset", 'zip', "/content/final_dataset")

!zip -r final_dataset.zip /content/final_dataset

import shutil

shutil.copytree("/content/dataset/train/labels",
                "/content/processed/labels",
                dirs_exist_ok=True)

print("Labels copied")

import os
from sklearn.model_selection import train_test_split

image_path = "/content/processed_dataset/images"
images = os.listdir(image_path)

train_imgs, temp_imgs = train_test_split(images, test_size=0.3, random_state=42)
val_imgs, test_imgs = train_test_split(temp_imgs, test_size=0.5, random_state=42)

print("Train:", len(train_imgs))
print("Validation:", len(val_imgs))
print("Test:", len(test_imgs))

from google.colab import files
files.download("final_dataset.zip")

