# -*- coding: utf-8 -*-
"""milestone 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1dbdGM93hGcKoMpr8apToKJ_WI7tGZN
"""

!pip install torch torchvision matplotlib

!pip install ultralytics

from google.colab import drive
drive.mount('/content/drive')

import os
import zipfile

# Define the path to the zipped dataset
ZIP_FILE_PATH = "/content/drive/MyDrive/final_dataset (1).zip"

# Define the directory where you want to extract the dataset
EXTRACT_PATH = "/content/final_dataset_extracted"

# Create the extraction directory if it doesn't exist
if not os.path.exists(EXTRACT_PATH):
    os.makedirs(EXTRACT_PATH)

print(f"Attempting to unzip {ZIP_FILE_PATH} to {EXTRACT_PATH}...")
try:
    with zipfile.ZipFile(ZIP_FILE_PATH, 'r') as zip_ref:
        zip_ref.extractall(EXTRACT_PATH)
    print("Extraction complete!")

    # After extraction, try to find the actual base path within the extracted directory
    # This assumes the zip contains a single top-level folder, which is common.
    # You might need to adjust this if the structure is different.
    extracted_contents = os.listdir(EXTRACT_PATH)
    if len(extracted_contents) == 1 and os.path.isdir(os.path.join(EXTRACT_PATH, extracted_contents[0])):
        # If there's one top-level directory, that's likely the true base path
        # Based on the previous output, it seems to be /content/final_dataset_extracted/content/final_dataset
        BASE_PATH = os.path.join(EXTRACT_PATH, extracted_contents[0], 'final_dataset') # Corrected path
    else:
        # Otherwise, the extraction path itself might be the base, or it's more complex
        BASE_PATH = EXTRACT_PATH # Default to extraction path, user might need to adjust

    print(f"Deduced BASE_PATH after extraction: {BASE_PATH}")

    # --- New Diagnostic Code: List contents of the deduced BASE_PATH ---
    if os.path.exists(BASE_PATH):
        print(f"Contents of deduced BASE_PATH ({BASE_PATH}):")
        for item in os.listdir(BASE_PATH):
            print(f"  - {item}")
    else:
        print(f"Error: Deduced BASE_PATH '{BASE_PATH}' does not exist. Cannot list its contents.")
    # --- End New Diagnostic Code ---

except FileNotFoundError:
    print(f"Error: ZIP file not found at '{ZIP_FILE_PATH}'. Please check the path.")
except Exception as e:
    print(f"An error occurred during extraction: {e}")

# --- Diagnostic Code (from original cell, modified to use new BASE_PATH) --- #
if not os.path.exists(BASE_PATH):
    print(f"Error: BASE_PATH '{BASE_PATH}' does not exist after extraction.")
    print("Please check the extracted structure or manually set BASE_PATH.")
    # No need to list MyDrive again, as we just tried to extract
    raise FileNotFoundError(f"BASE_PATH not found after extraction: {BASE_PATH}")
# --- End Diagnostic Code --- #

TRAIN_IMAGE_DIR = os.path.join(BASE_PATH, "train/images")
TRAIN_MASK_DIR  = os.path.join(BASE_PATH, "train/labels")  # Corrected: adjust to 'labels' folder

VAL_IMAGE_DIR = os.path.join(BASE_PATH, "val/images")
VAL_MASK_DIR  = os.path.join(BASE_PATH, "val/masks")      # create if missing

TEST_IMAGE_DIR = os.path.join(BASE_PATH, "test/images")
TEST_MASK_DIR  = os.path.join(BASE_PATH, "test/masks")    # optional

# Check contents
print("Checking contents with updated BASE_PATH:")
print("Train images:", len(os.listdir(TRAIN_IMAGE_DIR)))
print("Train masks:", len(os.listdir(TRAIN_MASK_DIR)))
print("Validation images:", len(os.listdir(VAL_IMAGE_DIR)))
if os.path.exists(VAL_MASK_DIR):
    print("Validation masks:", len(os.listdir(VAL_MASK_DIR)))
else:
    print("Validation masks folder does not exist")

import shutil
import random
import os

# Explicitly set BASE_PATH to the correctly extracted location
BASE_PATH = "/content/final_dataset_extracted/content/final_dataset"

# Redefine directory variables based on the correct BASE_PATH
TRAIN_IMAGE_DIR = os.path.join(BASE_PATH, "train/images")
TRAIN_MASK_DIR  = os.path.join(BASE_PATH, "train/labels")

VAL_IMAGE_DIR = os.path.join(BASE_PATH, "val/images")
VAL_MASK_DIR  = os.path.join(BASE_PATH, "val/masks")

os.makedirs(VAL_IMAGE_DIR, exist_ok=True)
os.makedirs(VAL_MASK_DIR, exist_ok=True)

TRAIN_IMG_FILES = os.listdir(TRAIN_IMAGE_DIR)
random.seed(42)
VAL_SAMPLE_FILES = random.sample(TRAIN_IMG_FILES, k=int(0.2*len(TRAIN_IMG_FILES)))  # 20% for val

for img_name in VAL_SAMPLE_FILES:
    # Move image
    shutil.move(os.path.join(TRAIN_IMAGE_DIR, img_name),
                os.path.join(VAL_IMAGE_DIR, img_name))
    # Move corresponding mask
    mask_name = img_name.replace('.jpg', '.txt')  # Assuming mask has .txt extension
    src_mask = os.path.join(TRAIN_MASK_DIR, mask_name)
    dst_mask = os.path.join(VAL_MASK_DIR, mask_name)
    if os.path.exists(src_mask):
        shutil.move(src_mask, dst_mask)
    else:
        print(f"Warning: Mask for {img_name} not found at {src_mask}")

print("Validation set created!")
print("Validation images:", len(os.listdir(VAL_IMAGE_DIR)))
print("Validation masks:", len(os.listdir(VAL_MASK_DIR)))

import torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import torchvision.transforms as transforms
import numpy as np
import os
import cv2 # Import cv2 for polygon drawing

class SegmentationDataset(Dataset):
    def __init__(self, image_filepaths, mask_filepaths, transform=None, target_size=(256, 256)):
        self.image_filepaths = image_filepaths
        self.mask_filepaths = mask_filepaths
        self.transform = transform
        self.target_size = target_size

    def __len__(self):
        return len(self.image_filepaths)

    def __getitem__(self, idx):
        img_path = self.image_filepaths[idx]
        mask_path = self.mask_filepaths[idx]

        # Load image
        image = Image.open(img_path).convert("RGB")
        original_img_w, original_img_h = image.size

        # Create empty mask (numpy array)
        mask_np = np.zeros((original_img_h, original_img_w), dtype=np.uint8)

        # Parse the .txt mask file (assuming YOLO segmentation format: class_id x1 y1 x2 y2 ... xn yn)
        try:
            with open(mask_path, 'r') as f:
                lines = f.readlines()
                for line in lines:
                    parts = line.strip().split()
                    if not parts:
                        continue

                    # Assuming first part is class_id, rest are normalized polygon coordinates
                    # class_id = int(parts[0]) # If you need class_id, store it. For binary, we just draw.
                    polygon_coords_normalized = list(map(float, parts[1:]))

                    # Convert normalized coords to pixel coords
                    polygon_points = []
                    for i in range(0, len(polygon_coords_normalized), 2):
                        x = int(polygon_coords_normalized[i] * original_img_w)
                        y = int(polygon_coords_normalized[i+1] * original_img_h)
                        polygon_points.append((x, y))

                    if polygon_points:
                        pts = np.array(polygon_points, np.int32)
                        pts = pts.reshape((-1, 1, 2))
                        cv2.fillPoly(mask_np, [pts], 1) # Fill with 1 (foreground)
        except Exception as e:
            print(f"Warning: Could not parse mask file {mask_path}. Error: {e}. Returning empty mask.")
            # If parsing fails, mask_np remains all zeros of original size

        # Resize image and numpy mask to target_size
        image = image.resize(self.target_size)
        mask_pil = Image.fromarray(mask_np).resize(self.target_size, Image.NEAREST)

        # Apply torchvision.transforms.ToTensor() to image and mask
        # transforms.ToTensor() scales image pixels to [0,1]
        image_tensor = transforms.ToTensor()(image)

        # Convert mask to Tensor, scale to [0,1] if it's already 0/1, and ensure float32
        mask_tensor = torch.tensor(np.array(mask_pil), dtype=torch.float32)

        return image_tensor, mask_tensor

BATCH_SIZE = 4

# Defining BASE_PATH and other directory variables explicitly as they were deleted.
BASE_PATH = "/content/final_dataset_extracted/content/final_dataset"
TRAIN_IMAGE_DIR = os.path.join(BASE_PATH, "train/images")
TRAIN_MASK_DIR  = os.path.join(BASE_PATH, "train/labels")
VAL_IMAGE_DIR   = os.path.join(BASE_PATH, "val/images")
VAL_MASK_DIR    = os.path.join(BASE_PATH, "val/masks")
TEST_IMAGE_DIR  = os.path.join(BASE_PATH, "test/images")
TEST_MASK_DIR   = os.path.join(BASE_PATH, "test/masks")

# Re-create matched lists (as they were deleted and needed here)
# --- Fixing Data Mismatch: Training Set ---
train_images_filenames = [f for f in os.listdir(TRAIN_IMAGE_DIR) if f.endswith(('.jpg', '.png', '.jpeg'))]
train_masks_filenames = [f for f in os.listdir(TRAIN_MASK_DIR) if f.endswith(('.txt', '.png', '.jpeg'))]

matched_train_images = []
matched_train_masks = []

for img_name in train_images_filenames:
    base_name = os.path.splitext(img_name)[0] # Get filename without extension
    mask_name_txt = base_name + '.txt'

    if mask_name_txt in train_masks_filenames:
        matched_train_images.append(os.path.join(TRAIN_IMAGE_DIR, img_name))
        matched_train_masks.append(os.path.join(TRAIN_MASK_DIR, mask_name_txt))

# --- Fixing Data Mismatch: Validation Set ---
val_images_filenames = [f for f in os.listdir(VAL_IMAGE_DIR) if f.endswith(('.jpg', '.png', '.jpeg'))]
val_masks_filenames = [f for f in os.listdir(VAL_MASK_DIR) if f.endswith(('.txt', '.png', '.jpeg'))]

matched_val_images = []
matched_val_masks = []

for img_name in val_images_filenames:
    base_name = os.path.splitext(img_name)[0]
    mask_name_txt = base_name + '.txt'

    if mask_name_txt in val_masks_filenames:
        matched_val_images.append(os.path.join(VAL_IMAGE_DIR, img_name))
        matched_val_masks.append(os.path.join(VAL_MASK_DIR, mask_name_txt))


# Training dataset
train_dataset = SegmentationDataset(matched_train_images, matched_train_masks)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, drop_last=True)

# Validation dataset
val_dataset = SegmentationDataset(matched_val_images, matched_val_masks)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)

# Verify
print("Train samples:", len(train_dataset))
print("Val samples:", len(val_dataset))

images, masks = next(iter(train_loader))
print("Image batch shape:", images.shape)
print("Mask batch shape:", masks.shape)

import torch.nn as nn
import torchvision.models.segmentation as segmentation

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load pretrained DeepLabV3
model = segmentation.deeplabv3_resnet50(pretrained=True)
# Adjust final classifier for 2 classes (background + site)
model.classifier[4] = nn.Conv2d(256, 2, kernel_size=(1,1))
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

num_epochs = 5

for epoch in range(num_epochs):
    model.train()
    train_loss = 0

    for images, masks in train_loader:
        images = images.to(device)
        masks  = masks.to(device)

        if len(masks.shape) == 4:
            masks = masks.squeeze(1)
        masks = masks.long()

        outputs = model(images)['out']
        loss = criterion(outputs, masks)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {train_loss/len(train_loader):.4f}")

model.eval()
val_loss = 0

with torch.no_grad():
    for images, masks in val_loader:
        images = images.to(device)
        masks  = masks.to(device)

        if len(masks.shape) == 4:
            masks = masks.squeeze(1)
        masks = masks.long()

        outputs = model(images)['out']
        loss = criterion(outputs, masks)
        val_loss += loss.item()

print(f"Validation Loss: {val_loss/len(val_loader):.4f}")

import os

SAVE_DIR = "/content/drive/MyDrive/final dataset"
# Create the directory if it doesn't exist
os.makedirs(SAVE_DIR, exist_ok=True)

torch.save(model.state_dict(), os.path.join(SAVE_DIR, "deeplabv3_segmentation.pth"))
print("Segmentation model saved to Google Drive!")

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

!ls

!pip install -r requirements.txt

!ls /content/drive/MyDrive

!ls "/content/drive/MyDrive/final dataset"

!ls "$TRAIN_IMAGE_DIR"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dataset.yaml
# path: /content/final_dataset_extracted/content/final_dataset
# 
# train: train/images
# val: val/images
# test: test/images
# 
# names:
#   0: buildings
#   1: roadline
#   2: vegetation
#   3: water
#   4: other
#   5: unknown_5 # Added to resolve IndexError: index 6 out of bounds
#   6: unknown_6 # Added to resolve IndexError: index 6 out of bounds

# Commented out IPython magic to ensure Python compatibility.
from ultralytics import YOLO

# Ensure we are in the yolov5 directory if not already
# %cd /content/yolov5

model = YOLO("yolov8n.pt")

model.train(
    data="dataset.yaml",
    epochs=150, # Increased epochs for better training
    imgsz=640,
    batch=16,
    name="train_7_classes" # Give a new name to the training run to avoid overwriting previous runs
)

from ultralytics import YOLO
import os
from IPython.display import Image, display

# Load model
model_path = "runs/detect/train_7_classes/weights/best.pt"  # Corrected path
model = YOLO(model_path)

# Run prediction
results = model.predict(
    source="/content/final_dataset_extracted/content/final_dataset/test/images",
    imgsz=640,
    conf=0.25,
    save=True,
    save_txt=True
)

# \u2705 Correct folder
predict_runs_dir = "runs/detect"

# Find latest predict folder
predict_dirs = [d for d in os.listdir(predict_runs_dir) if "predict" in d]
predict_dirs.sort(key=lambda x: os.path.getmtime(os.path.join(predict_runs_dir, x)), reverse=True)

if predict_dirs:
    latest_predict_run = os.path.join(predict_runs_dir, predict_dirs[0])
    print(f"Latest prediction results saved to: {latest_predict_run}")

    # Display images
    output_images = [f for f in os.listdir(latest_predict_run) if f.endswith(('.jpg', '.png', '.jpeg'))]

    for img in output_images[:5]:  # show first 5 images
        display(Image(filename=os.path.join(latest_predict_run, img)))
else:
    print("No prediction folders found.")

import os

for root, dirs, files in os.walk("runs"):
    for file in files:
        if file == "best.pt":
            print(os.path.join(root, file))

# After the previous training run (named 'train_7_classes') completes,
# the best model will likely be saved in 'runs/detect/train_7_classes/weights/best.pt'.
# You might need to verify the exact path by checking the 'runs/detect/' directory
# if the name 'train_7_classes' was already taken or modified by Ultralytics.

!python val.py \
--weights runs/detect/train_7_classes/weights/best.pt \
--data dataset.yaml \
--img 640

from google.colab import files
files.download('runs/detect/train_7_classes/weights/best.pt')

from google.colab import files
files.download('runs/detect/train_7_classes/results.png')

